modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/CuboidModding/TeaBridge/issues"

[[mods]]
modId = "teabridge"
version = "${version}"
displayName = "TeaBridge"
description = "A simple survival friendly MC -> Discord chat bridge"
authors = "CuboidModding"
credits = "Maximumpower55, asoji"
displayURL = "http://cuboid.me/modding"

[[mixins]]
config = "teabridge-common.mixins.json"

[[mixins]]
config = "teabridge-neoforge.mixins.json"

[[dependencies.teabridge]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.teabridge]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"
