name: Gradle build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PUBLISH_SUFFIX: snapshots
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: Get short SHA
        id: short_sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildOrPublish

      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifact-${{steps.short_sha.outputs.sha8}}
          path: build/libs/